# Hyperparameters for training
model_hp:
  model_id: Qwen/Qwen2.5-VL-3B-Instruct
  MIN_PIX: 256 
  MAX_PIX: 1280


training_hp:
  batch_size: 8
  bf16: true
  device: cuda
  max_epochs: 10
  lr: 2e-4
  check_val_every_n_epoch: 2
  gradient_clip_val: 1.0
  accumulate_grad_batches: 8
  num_nodes: 1
  warmup_steps: 50
  devices: 0
  accelerator: gpu
  result_path: "qwen25-3b-instruct"



dataloader: 
  batch_size: 8
  num_workers: 4
  shuffle: true
  pin_memory: true

model: train # test , resume , train
system_message: You are a Vision Language Model specialized in extracting structured data from visual representations of palette manifests. Your task is to analyze the provided image of a palette manifest and extract the relevant information into a well-structured JSON format. The palette manifest includes details such as item names, quantities, dimensions, weights, and other attributes. Focus on identifying key data fields and ensuring the output adheres to the requested JSON structure. Provide only the JSON output based on the extracted information. Avoid additional explanations or comments.

# laod data path
dataset_path: assets/dataset

